# Generated by Django 3.2.7 on 2021-09-27 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20210927_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='sexo',
            new_name='gender',
        ),
    ]
