# Generated by Django 3.2.7 on 2021-10-21 04:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_rename_sexo_client_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2021, 10, 21, 1, 19, 22, 614292)),
        ),
    ]
